UrlShortener/config/routes.rb
Rails.application.routes.draw do
  resources :urls

  root 'urls#index'

  get 'urls/' => 'urls#index'
  get ':id' => 'urls#link'
  get 'short/:url_short' => 'urls#link_short'

end

UrlShortener/app/models/url.rb
class Url < ActiveRecord::Base
  validates :url_short, uniqueness: true
end

UrlShortener/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

UrlShortener/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:link, :destroy]
  before_action :set_url_short, only: [:link_short]
  # before_action :create_url_short, only: [:new]

  def index
    @urls = Url.all
  end

  def new
    @url_short = [*('a'..'z'),*('0'..'9')].sample(5).join
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    if @url.save
      redirect_to urls_path
    end
  end

  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_path }
    end
  end

  def link
    redirect_to @url.url_long
  end

  def link_short
    redirect_to @url.url_long
  end

  private

  def set_url
    @url = Url.find(params[:id])
  end

  def set_url_short
    @url = Url.find_by(url_short: params[:url_short])
  end

  # def create_url_short
  #   @url_short = [*('a'..'z'),*('0'..'9')].sample(5).join
  # end

  def url_params
    params.require(:url).permit(:url_long, :url_short)
  end

end

UrlShortener/app/helpers/application_helper.rb
module ApplicationHelper
end

UrlShortener/app/helpers/urls_helper.rb
module UrlsHelper
end

UrlShortener/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

UrlShortener/app/views/urls/create.html.erb
You shouldn't be here

UrlShortener/app/views/urls/index.html.erb
<h2>Shortened URLs</h2>

<%= link_to "Generate Short URL", new_url_path %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Long URL</th>
      <th>Shortened</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.id %></td>
        <td><%= url.url_long %></td>
        <td><%= url.url_short %></td>
        <td><%= link_to 'Destroy', url, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>Input your url ID at the end of this url => localhost:3000/</p>
<p><strong>OR</strong></p>
<p>Input your shortened url at the end of this url => localhost:3000/short/</p>

UrlShortener/app/views/urls/new.html.erb
<h2>New Shortened URL</h2>

<%= form_for @url do |f| %>
  <%= f.label "Enter url here:" %>
  <br>
  <%= f.text_field :url_long %>
  <br>
  <%= f.hidden_field :url_short, value: @url_short %>
  <%= f.submit "Generate short" %>
<% end %>