goodschooler/config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'
  get '/get' => 'home#get', school: "wyncode"
  get '/special' => 'home#get', special: true
  post '/post' => 'home#post'

  get 'home/:username' => 'home#get'

  get '/login' => 'home#login'
  get '/logout' => 'home#logout'

  get '/redirector' => 'home#redirector'

  get '/private' => 'home#private'

end

goodschooler/app/models/code_school.rb
class CodeSchool < ActiveRecord::Base
  has_many :users
  has_many :projects, through: :users
end

goodschooler/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

goodschooler/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

goodschooler/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :code_school
  has_one :profile
  has_many :projects
  validates :email, presence: true

scope :active, -> {where(active: true)}
  # def self.active
  #   where(active: true)
  # end

scope :cohort, -> (number) {where(cohort: number)}
  # def self.cohort(number)
  #   where(cohort: number)
  # end

  def self.active_cohort(number)
    active.cohort(number)
  end

  # def to_s
  #   "This is #{self.class} whose name is #{}"
  # end
end

goodschooler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def in_logged_in?
    not session[:user_id].nil?
  end
  def redirect_unless_logged_in
    unless logged_in
      redirect_to root_path, alert: "You must be logged in to see this page."
    end
  end
end

goodschooler/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # login

    # logout

    @message = "You are currently "
    @message += if session[:user_id]
      'logged in.'
    else
      'logged out.'
    end

    # flash.now[:alert] = "Error!!1"

    @users = User.all
    @user = User.first
  end

  def login
    session[:user_id] = 1
    # flash[:notice] = "You have just logged in."
    redirect_to :back, notice: "You're in!"
    # redirect_to
  end

  before_action :redirect_unless_logged_in

  def private
    render :index
  end

  def logout
    session.delete(:user_id)
    # flash[:alert] = "You have just logged out."
    redirect_to :back, alert: "You've been kicked out."
  end

  def redirector
    redirect_to root_path
  end

  def post
    render plain: params.to_json
    # render plain: params[:user][:name]
  end

  def get
    render plain: params.to_json
  end

end

goodschooler/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

goodschooler/app/helpers/application_helper.rb
module ApplicationHelper
end

goodschooler/app/helpers/home_helper.rb
module HomeHelper
end

goodschooler/app/helpers/users_helper.rb
module UsersHelper
end

goodschooler/app/views/home/_user.html.erb
<div id="user_<%= user.id %>">
Hello <%= user.name %>!<br>
</div>

goodschooler/app/views/home/_users.html.erb
<% @users.each do |user| %>
  Hello <%= user.name %><br>
<% end %>

goodschooler/app/views/home/index.html.erb
<% flash.each do |type, msg| %>
<%= content_tag :div, msg, class: type %>
<% end %>
<br>
<h1>Hello World</h1>

<%= @message %>
<br>
<%= link_to 'Login', login_path %>
<br>
<%= link_to 'Logout', logout_path %>








<%#= Time.now %><br>
<%#= render partial: 'user', collection: @users %>


<!-- <h2>Edit User</h2> -->
<%#= form_for (@user) do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name %>

  <%#= f.label :active %>
  <%#= f.check_box :active %>

  <%#= f.label :name %>
  <%#= f.password_field :name %>

  <%#= f.label :cohort %>
  <%#= f.select :cohort, 1..9 %>

  <%#= f.label :name %>
  <%#= f.email_field :name %>

  <%#= f.label :name %>
  <%#= f.url_field :name %>

  <%#= f.label :cohort %>
  <%#= f.number_field :cohort %>

  <%#= f.label :name %>
  <%#= f.color_field :name %>

  <%#= f.submit "Update this User" %>
<%# end %>

goodschooler/app/views/home/index2.html.erb
<h1>User List</h1>

<%= Time.now %><br>

<h4>Helpers (helper.sfhlguhl in console):</h4>

<%= time_ago_in_words @user.updated_at %><br>
<%= number_to_percentage 90 %><br>
<%= number_to_phone 1231231234 %><br>
number = 145246425736
<%= number_to_currency number %><br>
<%= number_to_human_size number %><br>
<%= number_with_delimiter number %><br>
<%= number_with_precision number %><br>
<%= pluralize 3, "goose" %><br>


<%= render 'users' %>

goodschooler/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

goodschooler/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

goodschooler/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

goodschooler/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

goodschooler/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>